### ISSUE TITLE
shouldBeCalled being true even when not called

### ISSUE THREAD

**Issue by pedrofornaza** [phpspec/prophecy#251] opened 2016-01-30 13:41 UTC
Ive made a gist to illustrate my problem: https://gist.github.com/pedrofornaza/b819977e5415a0fc1643

The 'releaseEvents' should be called, but its not. The tests works even if i comment all the try body. The test fails if i use a spy (shouldHaveBeenCalled).

I did something wrong is that a bug?

Thanks in advance. :)

**Comment by aik099** [comment] 2016-01-31 09:15
In which way you're using Prophecy:

1. via PHPUnit's own integration
2. via manual PHPUnit integration
3. via PHPSpec

?

If it's the 2nd case, then I'm suspecting that `->checkPredictions()` method isn't being called to verify expectations.

**Comment by pedrofornaza** [comment] 2016-01-31 12:27
Im using 1. From my composer.lock:

"name": "phpunit/phpunit",
"version": "4.8.21",

"name": "phpspec/prophecy",
"version": "v1.5.0",

**Comment by kekko1212** [comment] 2016-02-09 14:46
Here the same exact problem. Using Prophecy integrated in PHPUnit.

If I manually go for a checkPredictions call in the teardown (overriding the $prophet var that is private) everything works as should be.

Notice that only the assertions on the method calls aren't working. 
The expectations on the returns (e.g. `->willReturn()`) or the expected arguments are working properly.

This is my composer.json content

```
"phpunit/phpunit": "5.1",
"phpspec/prophecy": "dev-master"
```

**Comment by kekko1212** [comment] 2016-02-09 15:08
Ok now I went a little bit more in a deep and I found the reason for this "strange" behaviour.

`vendor/phpunit/phpunit/src/Framework/TestCase.php:1008`

```
            try {
                $this->prophet->checkPredictions();
            } catch (Throwable $t) {
                /* Intentionally left empty */
            } catch (Exception $e) {
                /* Intentionally left empty */
            }
```

the exception for the failure is correctly thrown, but the catch does simply nothing with the exception, so it is failing silently.

The real strange thing are those comments. 

Do you "intentionally" wanted a red test to stay green? :)

**Comment by aik099** [comment] 2016-02-09 15:34
It's PHPUnit problem obviously. I recommend posting in there as well. Looking through PHPUnit commit history (at point where this code was created) might explain (in commit message) why this was done like this.

**Comment by jakzal** [comment] 2016-02-09 15:37
@kekko1212 would you mind to check what type of an exception is thrown and ignored exactly? Including the message?

**Comment by aik099** [comment] 2016-02-09 15:38
Looking at code below mentioned one shows ` if (isset($e)) {` which does handle that exception correctly.

And yes, the problem is that `Throwable $t` should be `Throwable $e` instead. Fixed in 5.x (but not 5.0) and not 4.8 releases of PHPUnit.

**Comment by kekko1212** [comment] 2016-02-09 15:47
Yes, it's a phpunit issue (only related to phpspec). The fix in PHPUnit 5.x solves this issue.

Thanks

**Closed** 2016-02-15 07:29 UTC
